namespace Stats
{
    public enum StatName
    {
        Weight,
        Power,
        Speed,
        EnergyReserveRatio,
        LungsCapacity,
        EnergyEfficiencyRatio,
        SprintSpeedPreferenceRatio,
        Hunger,
        HungerDecay, 
        CaloriesToHungerConversionRate,
        HungerThreshold,
        MaxHunger,
        Thirst,
        MaxThirst,
        ReproductionNeedThreshold,
        ReproductionNeedDecay,
        EyeSight,
        EatingSpeed,
        IsMale,
        SprintSpeed,
        BaseSpeed,
        RunSpeed,
        EnergyConsumptionPerSecond,
        Calories,
        MaxCalorieCount,
        MetabolismRatePerSec,
        MaxWeight,
        HungerDC,
        HungerDecayInterval
    }
}